name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git identity
        run: |
          git config --global user.name "AyushSingh360"
          git config --global user.email "ayushsingh21109@gmail.com"
      - name: Sync accepted submissions
        uses: joshcai/leetcode-sync@master
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: leetcode
          verbose: true
          commit-header: "[LeetCode Sync]"
